{"asctime": "2023-12-27T18:51:04Z", "levelname": "ERROR", "name": "utils.log_utils", "module": "app_utils", "funcName": "read_data", "lineno": 31, "message": "Error reading file: [Errno 2] No such file or directory: '.data/input.txt'"}
{"asctime": "2023-12-27T18:51:04Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 42, "message": "Custom Exception caught: fileReader::read_data(): FileNotFoundError - [Errno 2] No such file or directory: '.data/input.txt' [Line No 22]"}
{"asctime": "2023-12-28T09:34:46Z", "levelname": "ERROR", "name": "utils.log_utils", "module": "app_utils", "funcName": "read_data", "lineno": 31, "message": "Error reading file: expected str, bytes or os.PathLike object, not list"}
{"asctime": "2023-12-28T09:34:46Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 43, "message": "Custom Exception caught: fileReader::read_data(): TypeError - expected str, bytes or os.PathLike object, not list [Line No 22]"}
{"asctime": "2023-12-28T09:39:10Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 54, "message": "Error : fileProcessor::process_file(): TypeError - expected str, bytes or os.PathLike object, not list [Line No 40]"}
{"asctime": "2023-12-28T09:40:15Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 55, "message": "Error : fileProcessor::process_file(): TypeError - expected str, bytes or os.PathLike object, not list [Line No 40]"}
{"asctime": "2023-12-28T09:42:53Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 55, "message": "Error : fileProcessor::process_file(): TypeError - expected str, bytes or os.PathLike object, not list [Line No 40]"}
{"asctime": "2023-12-28T09:43:09Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 55, "message": "Error : fileProcessor::process_file(): TypeError - expected str, bytes or os.PathLike object, not list [Line No 39]"}
{"asctime": "2023-12-28T09:44:54Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 66, "message": "Error : fileProcessor::process_file(): AttributeError - 'FileProcessor' object has no attribute 'input_patterns' [Line No 40]"}
{"asctime": "2023-12-28T09:45:37Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 63, "message": "Error : fileProcessor::process_file(): AttributeError - 'FileProcessor' object has no attribute 'input_patterns' [Line No 40]"}
{"asctime": "2023-12-28T09:45:54Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 63, "message": "Error : fileProcessor::process_file(): ValueError - Input pattern must be a string. [Line No 43]"}
{"asctime": "2023-12-28T09:46:24Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 63, "message": "Error : fileProcessor::process_file(): ValueError - Input pattern must be a string. [Line No 43]"}
{"asctime": "2023-12-28T09:47:14Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 64, "message": "Error : fileProcessor::process_file(): ValueError - Input pattern must be a string. [Line No 43]"}
{"asctime": "2023-12-28T09:47:45Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 64, "message": "Error : fileProcessor::process_file(): ValueError - Input pattern must be a string. [Line No 44]"}
{"asctime": "2023-12-28T09:49:21Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 64, "message": "Error : fileProcessor::process_file(): ValueError - Input pattern must be a string. [Line No 44]"}
{"asctime": "2023-12-28T10:04:02Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 65, "message": "Error : fileProcessor::process_file(): TypeError - expected str, bytes or os.PathLike object, not list [Line No 41]"}
{"asctime": "2023-12-28T10:04:59Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 65, "message": "Error : fileProcessor::process_file(): TypeError - expected str, bytes or os.PathLike object, not list [Line No 41]"}
{"asctime": "2023-12-28T10:08:24Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 73, "message": "Error : fileProcessor::process_file(): TypeError - check_infile_type() takes 1 positional argument but 2 were given [Line No 44]"}
{"asctime": "2023-12-31T19:24:22Z", "levelname": "CRITICAL", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 64, "message": "data/input.txt : File processing successful..!"}
{"asctime": "2023-12-31T19:25:20Z", "levelname": "CRITICAL", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 64, "message": "data/input.txt : File processing successful..!"}
{"asctime": "2023-12-31T19:27:45Z", "levelname": "CRITICAL", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 65, "message": "data/input.txt : File processing successful..!"}
{"asctime": "2023-12-31T19:29:20Z", "levelname": "CRITICAL", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 65, "message": "data/input.txt : File processing successful..!"}
{"asctime": "2024-02-03T20:43:57Z", "levelname": "ERROR", "name": "demo_project.app.utils.app_utils", "module": "app_utils", "funcName": "save_data", "lineno": 158, "message": "Error saving data to file: [Errno 2] No such file or directory: 'data/output.txt'"}
{"asctime": "2024-02-03T20:43:57Z", "levelname": "ERROR", "name": "demo_project.app.utils.app_utils", "module": "app_utils", "funcName": "save_data", "lineno": 158, "message": "Error saving data to file: [Errno 2] No such file or directory: 'data/output.txt'"}
{"asctime": "2024-02-03T20:43:57Z", "levelname": "ERROR", "name": "demo_project.app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 67, "message": "Custom Exception caught: app_utils::save_data(): FileNotFoundError - [Errno 2] No such file or directory: 'data/output.txt' [Line No 150]"}
{"asctime": "2024-02-03T20:48:04Z", "levelname": "ERROR", "name": "demo_project.app.utils.app_utils", "module": "app_utils", "funcName": "save_data", "lineno": 158, "message": "Error saving data to file: [Errno 2] No such file or directory: 'data/output.txt'"}
{"asctime": "2024-02-03T20:48:04Z", "levelname": "ERROR", "name": "demo_project.app.utils.app_utils", "module": "app_utils", "funcName": "save_data", "lineno": 158, "message": "Error saving data to file: [Errno 2] No such file or directory: 'data/output.txt'"}
{"asctime": "2024-02-03T20:48:04Z", "levelname": "ERROR", "name": "demo_project.app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 66, "message": "Custom Exception caught: app_utils::save_data(): FileNotFoundError - [Errno 2] No such file or directory: 'data/output.txt' [Line No 150]"}
{"asctime": "2024-02-03T20:49:39Z", "levelname": "ERROR", "name": "demo_project.app.utils.app_utils", "module": "app_utils", "funcName": "save_data", "lineno": 158, "message": "Error saving data to file: [Errno 2] No such file or directory: '../../data/output.txt'"}
{"asctime": "2024-02-03T20:49:39Z", "levelname": "ERROR", "name": "demo_project.app.utils.app_utils", "module": "app_utils", "funcName": "save_data", "lineno": 158, "message": "Error saving data to file: [Errno 2] No such file or directory: '../../data/output.txt'"}
{"asctime": "2024-02-03T20:49:39Z", "levelname": "ERROR", "name": "demo_project.app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 66, "message": "Custom Exception caught: app_utils::save_data(): FileNotFoundError - [Errno 2] No such file or directory: '../../data/output.txt' [Line No 150]"}
{"asctime": "2024-02-03T20:54:01Z", "levelname": "ERROR", "name": "demo_project.app.utils.app_utils", "module": "app_utils", "funcName": "save_data", "lineno": 158, "message": "Error saving data to file: [Errno 2] No such file or directory: '../../data/output.txt'"}
{"asctime": "2024-02-03T20:54:01Z", "levelname": "ERROR", "name": "demo_project.app.utils.app_utils", "module": "app_utils", "funcName": "save_data", "lineno": 158, "message": "Error saving data to file: [Errno 2] No such file or directory: '../../data/output.txt'"}
{"asctime": "2024-02-03T20:54:01Z", "levelname": "ERROR", "name": "demo_project.app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 67, "message": "Custom Exception caught: app_utils::save_data(): FileNotFoundError - [Errno 2] No such file or directory: '../../data/output.txt' [Line No 150]"}
{"asctime": "2024-02-03T20:57:48Z", "levelname": "ERROR", "name": "demo_project.app.utils.app_utils", "module": "app_utils", "funcName": "save_data", "lineno": 158, "message": "Error saving data to file: [Errno 2] No such file or directory: '../../data/output.txt'"}
{"asctime": "2024-02-03T20:57:48Z", "levelname": "ERROR", "name": "demo_project.app.utils.app_utils", "module": "app_utils", "funcName": "save_data", "lineno": 158, "message": "Error saving data to file: [Errno 2] No such file or directory: '../../data/output.txt'"}
{"asctime": "2024-02-03T20:57:48Z", "levelname": "ERROR", "name": "demo_project.app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 68, "message": "Custom Exception caught: app_utils::save_data(): FileNotFoundError - [Errno 2] No such file or directory: '../../data/output.txt' [Line No 150]"}
{"asctime": "2024-02-03T21:07:20Z", "levelname": "ERROR", "name": "demo_project.app.utils.app_utils", "module": "app_utils", "funcName": "save_data", "lineno": 159, "message": "Error saving data to file: [Errno 2] No such file or directory: '../../data/output.txt'"}
{"asctime": "2024-02-03T21:07:20Z", "levelname": "ERROR", "name": "demo_project.app.utils.app_utils", "module": "app_utils", "funcName": "save_data", "lineno": 159, "message": "Error saving data to file: [Errno 2] No such file or directory: '../../data/output.txt'"}
{"asctime": "2024-02-03T21:07:20Z", "levelname": "ERROR", "name": "demo_project.app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 69, "message": "Custom Exception caught: app_utils::save_data(): FileNotFoundError - [Errno 2] No such file or directory: '../../data/output.txt' [Line No 150]"}
{"asctime": "2024-02-03T21:13:51Z", "levelname": "ERROR", "name": "demo_project.app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 76, "message": "Error : fileProcessor::process_file(): AttributeError - type object 'AppUtils' has no attribute 'logger' [Line No 65]"}
{"asctime": "2024-02-03T21:15:34Z", "levelname": "ERROR", "name": "demo_project.app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 76, "message": "Error : fileProcessor::process_file(): AttributeError - type object 'AppUtils' has no attribute 'logger' [Line No 65]"}
